export enum EconomicSector {
  RETAIL = 'RETAIL',
  SERVICES = 'SERVICES',
  INDUSTRY = 'INDUSTRY',
  CONSTRUCTION = 'CONSTRUCTION',
  HEALTHCARE = 'HEALTHCARE',
  AGRICULTURE = 'AGRICULTURE',
  TECHNOLOGY = 'TECHNOLOGY',
  OTHER = 'OTHER'
}
